fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
      address: "starslan-1@yandex.ru"
      sender_name: "vincent@vfac.fr"
  registration:
      confirmation:
          enabled: true
  resetting:
      email:
          from_email:
              address:        resetting@example.com
              sender_name:    Demo Resetting